### ISSUE TITLE
CalculatePasses returns unexpected results

### ISSUE THREAD

**Issue by edetoc** [1manprojects/one_Sgp4#10]
**Describe the bug**
I'm using CalculatePasses function to get upcoming visible passes (5 days) of the ISS for an observer's location but it returns unexpected results

**To Reproduce**

I'm using One_Sgp4 v1.0.5 (released December 2, 2018 ).  
TLE used :

ISS (ZARYA)             
1 25544U 98067A   19013.58677685  .00000299  00000-0  11878-4 0  9995
2 25544  51.6425  50.2106 0002416 284.1251 212.8292 15.53757701151234

Code used:

            //Coordinate of an observer on Ground lat, long, height(in meters)
            One_Sgp4.Coordinate observer = new Coordinate(48.8270 , 2.1887);   // VDA
            
            //Calculate the Next 5 Passes over a point
            //for a location, Satellite, StartTime, Accuracy in Seconds = 15sec, MaxNumber of Days = 5 Days, Wgs constant = WGS_84
            //Returns pass with Location, StartTime of Pass, EndTime Of Pass, Max Elevation in Degrees
            List<Pass> passes = One_Sgp4.SatFunctions.CalculatePasses(observer, tleISS, new EpochTime(DateTime.UtcNow), 15, 5, Sgp4.wgsConstant.WGS_84);
            foreach (var p in passes)
            {
                Debug.WriteLine(p.ToString());                                
            }

the above code returns the following results:		

Start Of Contact: 13.01.2019-21:22:46, End of Contact: 13.01.2019-22:00:46, Max Elevation: 81.132108075482
Start Of Contact: 13.01.2019-22:57:16, End of Contact: 13.01.2019-23:06:16, Max Elevation: 62.8306591872441
Start Of Contact: 13.01.2019-23:06:31, End of Contact: 13.01.2019-02:55:46, Max Elevation: 3140.63559205821
Start Of Contact: 13.01.2019-03:47:01, End of Contact: 13.01.2019-03:58:01, Max Elevation: 91.4952487663781
Start Of Contact: 13.01.2019-05:23:46, End of Contact: 13.01.2019-05:29:31, Max Elevation: 47.1628122069365
Start Of Contact: 13.01.2019-05:29:46, End of Contact: 13.01.2019-06:34:46, Max Elevation: 462.247040970672
Start Of Contact: 13.01.2019-20:32:16, End of Contact: 13.01.2019-21:53:01, Max Elevation: 122.496672327445
Start Of Contact: 13.01.2019-22:05:31, End of Contact: 13.01.2019-22:15:46, Max Elevation: 56.9892797360133
Start Of Contact: 13.01.2019-23:41:46, End of Contact: 13.01.2019-23:53:31, Max Elevation: 102.970356543472
Start Of Contact: 13.01.2019-01:18:16, End of Contact: 13.01.2019-01:27:31, Max Elevation: 80.4046104725208
Start Of Contact: 13.01.2019-01:27:46, End of Contact: 13.01.2019-05:12:31, Max Elevation: 4318.88294826637
Start Of Contact: 13.01.2019-06:10:46, End of Contact: 13.01.2019-06:12:16, Max Elevation: 8.29590168745457
Start Of Contact: 13.01.2019-06:12:31, End of Contact: 13.01.2019-06:12:46, Max Elevation: 5.64650943360117
Start Of Contact: 13.01.2019-21:14:01, End of Contact: 13.01.2019-21:27:01, Max Elevation: 48.1640876561404
Start Of Contact: 13.01.2019-22:49:31, End of Contact: 13.01.2019-22:57:01, Max Elevation: 59.1346820384278
Start Of Contact: 13.01.2019-22:57:16, End of Contact: 13.01.2019-02:06:46, Max Elevation: 3306.80427917464
Start Of Contact: 13.01.2019-02:07:01, End of Contact: 13.01.2019-03:55:46, Max Elevation: 2122.49435586353
Start Of Contact: 13.01.2019-05:16:46, End of Contact: 13.01.2019-05:21:16, Max Elevation: 37.211836643121
Start Of Contact: 13.01.2019-05:21:31, End of Contact: 13.01.2019-05:54:16, Max Elevation: 222.826964989532
Start Of Contact: 13.01.2019-20:23:01, End of Contact: 13.01.2019-20:55:01, Max Elevation: 59.0198862462301
Start Of Contact: 13.01.2019-21:57:46, End of Contact: 13.01.2019-22:10:46, Max Elevation: 94.0689317392554
Start Of Contact: 13.01.2019-23:34:01, End of Contact: 13.01.2019-23:40:46, Max Elevation: 56.369164202541
Start Of Contact: 13.01.2019-23:41:01, End of Contact: 13.01.2019-02:33:16, Max Elevation: 2816.34693645587
Start Of Contact: 13.01.2019-02:47:16, End of Contact: 13.01.2019-02:56:01, Max Elevation: 71.2467740644317
Start Of Contact: 13.01.2019-02:56:16, End of Contact: 13.01.2019-05:33:01, Max Elevation: 794.524838237632
Start Of Contact: 13.01.2019-19:32:31, End of Contact: 13.01.2019-20:48:31, Max Elevation: 100.488426074259
Start Of Contact: 13.01.2019-21:06:01, End of Contact: 13.01.2019-21:21:01, Max Elevation: 86.8978985296678
Start Of Contact: 13.01.2019-22:42:01, End of Contact: 13.01.2019-22:51:46, Max Elevation: 82.9325140612512
Start Of Contact: 13.01.2019-22:52:01, End of Contact: 13.01.2019-02:57:16, Max Elevation: 3012.18646462304
Start Of Contact: 13.01.2019-03:31:46, End of Contact: 13.01.2019-03:37:46, Max Elevation: 49.7877361843573
Start Of Contact: 13.01.2019-03:38:01, End of Contact: 13.01.2019-05:12:01, Max Elevation: 877.429238102212
Start Of Contact: 13.01.2019-05:12:16, End of Contact: 13.01.2019-05:15:31, Max Elevation: 23.1222498676525

However using https://heavens-above.com for same observer's location returns no visible pass for the coming days.

looking at the results above I'm surprised to see sometimes a significant amount of time between 'Start of Contact' and 'End of Contact' ,  a few examples:

Start Of Contact: 13.01.2019-03:38:01, End of Contact: 13.01.2019-05:12:01, Max Elevation: 877.429238102212
Start Of Contact: 13.01.2019-22:52:01, End of Contact: 13.01.2019-02:57:16, Max Elevation: 3012.18646462304
Start Of Contact: 13.01.2019-02:07:01, End of Contact: 13.01.2019-03:55:46, Max Elevation: 2122.49435586353

Also Max Elevation is very high as you can see.

**Expected behavior**
Would expect to see results aligned with heavens-above

**Comment by 1manprojects** [comment]
Thanks for the infos i will check into this issue as soon as possible and try to verify your described behavior.

**Comment by 1manprojects** [comment]
So I finally had time to check and yes there appears to be a critical error with that function calculating the exact times the satellite is visible from a certain observers position. This leads to completely wrong Elevation values and extreme long contact window time frames.
I will rewrite the function and reimplement it and will publish a new version in 1-2 weeks.

**Comment by edetoc** [comment]
Thank you. Great that you found the problem!

**Comment by 1manprojects** [comment]
fixed with version 1.0.7
