### ISSUE TITLE
Add more properties to the Pass class

### ISSUE THREAD

**Issue by edetoc** [1manprojects/one_Sgp4#11]
**Is your feature request related to a problem? Please describe.**
My [App ](https://www.microsoft.com/store/productId/9NBLGGH51634)actually issues HTTP queries to heavens-above.com to get upcoming pass details. I'd like to use One_Sgp4 library instead to achieve the same goal with same pass details.

**Describe the solution you'd like**
Would it be possible to augment the Pass class (https://github.com/1manprojects/one_Sgp4/blob/master/One_Sgp4/Pass.cs) with the same details as in screenshot below (which comes from heavens-above.com) ?

![image](https://user-images.githubusercontent.com/17158589/51111727-46975b80-17fd-11e9-9988-81214f29a143.png)

Thanks!

**Comment by 1manprojects** [comment]
Well it is possible and having more information availalbe is nice to have. I could implement such a feature at some point. However i can give you no time frame wen this could be.

**Comment by edetoc** [comment]
that's great. thanks for considering this enhancement.

**Comment by 1manprojects** [comment]
Details for passes were added and a new easier function to calculate passes was included. Thus closing this Issue
