### ISSUE TITLE
calcSatSubPoint returns inaccurate position

### ISSUE THREAD

**Issue by edetoc** [1manprojects/one_Sgp4#12]
**Describe the bug**
calcSatSubPoint returns inaccurate position

**To Reproduce**
I'm getting TLE for ISS (Norad Id 25544) from https://www.celestrak.com/NORAD/elements/stations.txt
I call calcSatSubPoint to get ISS position for a time.
I'm comparing today the ISS position calculated in my App using calcSatSubPoint function with http://www.esa.int/Our_Activities/Human_and_Robotic_Exploration/International_Space_Station/Where_is_the_International_Space_Station and I can see the ISS position differs significantly.

Here's a screenshot of my App (taken today 2/2/18 around 6:17pm French time)

![image](https://user-images.githubusercontent.com/17158589/52167138-ee29ee80-2716-11e9-9bb4-5f0ec4dc4fd2.png)

**Expected behavior**
Here's a screenshot taken at same time (just a few seconds later) of the ESA link mentioned above

![image](https://user-images.githubusercontent.com/17158589/52167141-f6822980-2716-11e9-8415-41612051dcab.png)

We can see the ISS position between both screenshots differs.

**Version(please complete the following information):**
- Device: Desktop 
 - OS: Windows 10 version 1809
 - Version 1.0.5 of One_Sgp4

**Comment by edetoc** [comment]
https://www.n2yo.com/?s=25544  gives also same position for ISS than http://www.esa.int/Our_Activities/Human_and_Robotic_Exploration/International_Space_Station/Where_is_the_International_Space_Station

**Comment by 1manprojects** [comment]
Related to Issue #10 and will be fixed soon.

**Comment by edetoc** [comment]
Have you managed to make any progress ? thank you in advance.

**Comment by 1manprojects** [comment]
Sorry, but i haven't had time until today to start investigating properly. Hopefully this will be fixed in 2 weeks however i cannot grantee that.

**Comment by edetoc** [comment]
Update: without making any changes to my App, I can see today that the ISS position is correctly computed (I'm comparing with http://www.esa.int/Our_Activities/Human_and_Robotic_Exploration/International_Space_Station/Where_is_the_International_Space_Station). So based on my observations, there are period of times (it can last weeks as far as I can see) where ISS position calculation is wrong, and then suddenly calculation becomes OK.

**Comment by 1manprojects** [comment]
Yes, I also observed this behavior and currently I do not have a good explanation for this. Multiple issues could lead to this behavior like errors in the TLE-data, error in the date calculation or parsing error of certain Tle-data sets etc. I don't know yet what the exact problem is and still investigating. But it appears that the calculations for the position of the Satellite returned wrong results thus all other calculations based on them were off.

**Comment by edetoc** [comment]
thanks. I agree, it seems to be a tricky one... for the TLE data I'm fetching
https://www.celestrak.com/NORAD/elements/stations.txt  each time I start my app. this  seems to be a commonly used source for TLE data.

**Comment by edetoc** [comment]
Have you made any progress? I can see the position of the ISS is wrong again in my app.

**Comment by 1manprojects** [comment]
Hello, Thanks for the Information again.
I could finally reproduce and observer the Error stated here.
The Time Calculation is off. Converting a UTC Date-Time to Epoch-Time returns a value that is off by 24 hours. Thus resulting in wrong positioning data being calculated. This is being triggered at certain dates Wenn switching from one month to another. I'm currently working on a fix but cannot promise when I'm done

**Comment by 1manprojects** [comment]
Version 1.0.7 solves this issue and will be available on Nuget shortly
