### ISSUE TITLE
EpochTime.toDateTime() raises Exception when seconds round to 60

### ISSUE THREAD

**Issue by RobertK66** [1manprojects/one_Sgp4#13]
Using a TLE with a DayOfYear generating a time with 59,6... seconds does not return correct ToDateTime() value. 

e.g. using 
var x = new EpochTime(2017, 326.59305107);
var d = x.toDateTime(); 
raises an Exception.

- Library Version 1.0.7

I already have a fix and will provide a pull request for it. I hope you will also accept my additional changes there ;-) .....

**Comment by 1manprojects** [comment]
fix was merged into master.
