### ISSUE TITLE
 Issues with spherical coordinates.

### ISSUE THREAD

**Issue by JudgeTredd** [1manprojects/one_Sgp4#15]
**Describe the bug**
I'm not sure if I'm missing something here but I don't get accurate azimuth/elevation values when comparing to other ISS locators.

Observer Lat/Long/Height is: 45.68338, -73.43246, 0

1.) Comparing ISS data the azimuth and elevation are off by varying amounts. The Lat/Long/Altitude of the satellite are correct.

2.) Pass values are strange both for duration and elevation:

Start Of Contact: 14.08.2019-16:06:16, End of Contact: 14.08.2019-16:14:46, Max Elevation: 153.799149518202
Start Of Contact: 14.08.2019-16:15:01, End of Contact: 14.08.2019-19:38:01, Max Elevation: 4170.55683568467
Start Of Contact: 14.08.2019-19:38:16, End of Contact: 14.08.2019-01:13:31, Max Elevation: 1726.2632728008
Start Of Contact: 14.08.2019-08:58:01, End of Contact: 14.08.2019-12:10:16, Max Elevation: 179.48558251804
Start Of Contact: 14.08.2019-12:10:31, End of Contact: 14.08.2019-15:16:46, Max Elevation: 985.429678273676
Start Of Contact: 14.08.2019-15:17:01, End of Contact: 14.08.2019-15:35:16, Max Elevation: 284.913716508419
Start Of Contact: 14.08.2019-15:35:31, End of Contact: 14.08.2019-23:02:01, Max Elevation: 3840.08671322694

**To Reproduce**

TLE data used were the most updated from Celestrak.

2. What function was called:

          //Calculate Sperical Coordinates from an Observer to Satellite
            //returns 3D-Point with range(km), azimuth(radians), elevation(radians) to the Satellite
            One_Sgp4.Point3d spherical = One_Sgp4.SatFunctions.calcSphericalCoordinate(observer, startTime, resultDataList[0]);

I used spherical.x spherical.y and spherical.z for altitude, azimuth and elevation.

![satissue](https://user-images.githubusercontent.com/54116543/63042787-bf948980-be98-11e9-8767-2e4ef38d363b.png)

Again not sure if I'm just missing something here.

Thank you,

**Comment by 1manprojects** [comment]
Thanks for the information,
I'm currently reworking the Pass Prediction to fix some issues that most likely you are having. At its current State (Master branch) the Calculations for the passes are off by around 6° which I'm still investigating. If I find the error I will release a new version. The current release (version 1.0.8) does not contain the newer Pass-Prediction.

**Comment by 1manprojects** [comment]
Found the Issue, the Coordinates of the Ground location were not correctly calculated for the calcSpericalCoordinate function. This has been fixed and a new Version as been published to Nuget.

**Comment by JudgeTredd** [comment]
You skilled man. Thanks for your hard work.
