### ISSUE TITLE
Unhandled exception error "Eccentricity is out of bounds"

### ISSUE THREAD

**Issue by ykhaled** [1manprojects/one_Sgp4#18]
**Describe the bug**
Crashing while running due to un-handeled exception error "Eccentricity is out of bounds". The TLE database is coming from celestrak.com (stations.txt).  I dont expect there to be any issue with the Eccentricity values. Not sure what I'm doing incorrectly?

**To Reproduce**
Simply compile and run the following code:

`List<Tle> tempSatList = null;
if (System.IO.File.Exists("stations.txt"))
{
tempSatList = ParserTLE.ParseFile("stations.txt");
}
EpochTime myTime = new EpochTime(DateTime.UtcNow);

foreach (var tleVar in tempSatList)
{
One_Sgp4.Sgp4 sgp4Propagator = new Sgp4(tleVar, Sgp4.wgsConstant.WGS_84);
sgp4Propagator.runSgp4Cal(myTime, myTime, 1);
var result = sgp4Propagator.getRestults()[0];
One_Sgp4.Coordinate satCoordinates = One_Sgp4.SatFunctions.calcSatSubPoint(myTime, result, Sgp4.wgsConstant.WGS_84);
logging.Comment(satCoordinates.getLatetude() + " : " + satCoordinates.getLongitude());
}`

**Parameter name**
Parameter name: Sgp4Calculation

**Database link**
[http://celestrak.com/NORAD/elements/stations.txt](url)

**Expected behavior**
The TLE details are correct. I expect the library to accept all stations in the database.

**Version:**
 - Version: 1.08

**Exception Unhandled**
System.ArgumentException
  HResult=0x80070057
  Message=ALTAIR PATHFINDER        -Eccentricity is out of bounds
Parameter name: Sgp4Calculation
  Source=One_Sgp4
  StackTrace:
   at One_Sgp4.Sgp4.calcSgp4()
   at One_Sgp4.Sgp4.runSgp4Cal(EpochTime starttime, EpochTime stoptime, Double step)
   at shr_parser_sharp.Controls.SatelliteControl.SatelliteControl_Load(Object sender, EventArgs e) in

**Comment by ykhaled** [comment]
I had to remove the troubling stations from the txt file (stations.txt) to stop the crashing. Maybe its an issue with your TLE Parser not reading the scientific notations properly.

**Comment by 1manprojects** [comment]
I assume you have tried to calculate the data of a satellite that is longer in orbit. If the TLE data is outdated or the satellites in question is no longer in orbit the calculation will in most cases throw an eccentricity out of bounds error. 

I cannot load the example file so im unable to check what data was used. If possible can you post the exact TLE data that cause the exception.

**Comment by ykhaled** [comment]
> I assume you have tried to calculate the data of a satellite that is longer in orbit. If the TLE data is outdated or the satellites in question is no longer in orbit the calculation will in most cases throw an eccentricity out of bounds error.
> 
> I cannot load the example file so im unable to check what data was used. If possible can you post the exact TLE data that cause the exception.

http://celestrak.com/NORAD/elements/stations.txt

**Comment by edetoc** [comment]
> I had to remove the troubling stations from the txt file (stations.txt) to stop the crashing. Maybe its an issue with your TLE Parser not reading the scientific notations properly.

I think I faced the same issue with stations.txt a while back. I'm now querying celestrak only for the satellite I need, in my case : https://celestrak.com/satcat/tle.php?CATNR=25544
With that, ParserTLE.ParseFile succeeds.

**Comment by 1manprojects** [comment]
The Error is thrown while calculating the orbital parameters of the "ALTAIR PATHFINDER" noradID: [42711U](https://www.n2yo.com/satellite/?s=42711) . 
This Satellite is no longer in orbit and has decayed. Calculating the position of the satellite is then no longer possible and an "Eccentricity is out of bounds" is thrown.
This behavior is expected and not an error parsing.
