### ISSUE TITLE
how to get Argument of periapsis and Semi major axis?

### ISSUE THREAD

**Issue by antoniohof** [1manprojects/one_Sgp4#25]
Hi, 

First thank you for the lib, its very useful!

Im trying to integrate it in my project,

but my simulator uses semi major axis and argument of periapsis to calculate orbits,

how can I get them from your tle object?

Or maybe how can I calculate them?

Thanks!

**Comment by antoniohof** [comment]
basically these two:		

<param name="argOfPerifocusDeg">Orbit argument of perifocus in degrees.
<param name="semiMajorAxis">Main axis semi width.

**Comment by antoniohof** [comment]
Ok I could ge tthe semi major axis like that, if anyone is interested: 
```
                float meanMotion = (float)tleList[i].getMeanMotion();
                float u = 3.986004418f * Mathf.Pow(10, 14);
                float n = (2.0f * meanMotion * (float)Math.PI) / 86400;

                double semiMajorAxis = (Mathf.Pow(u, 0.33333333f) / Mathf.Pow(n, 0.6666666f)) * 0.001;
```

**Comment by 1manprojects** [comment]
I would not recommend to just convert TLE-Data to another format since it would introduce uncertainties that would make future predictions not viable. For more information, you could read the following that explains the problems https://celestrak.com/columns/v04n05/#FAQ05

**Comment by 1manprojects** [comment]
If you really still want to convert TLE to Kepler Elements then you could follow the follwing guide. https://blog.hardinglabs.com/tle-to-kep.html
