### ISSUE TITLE
longitude of SatSubPoint result is wrong compre with PyEphem's sat.sublong

### ISSUE THREAD

**Issue by greenoaktree** [1manprojects/one_Sgp4#3]
List<One_Sgp4.Tle> tles =One_Sgp4.ParserTLE.ParseFile("iridium.txt");

            var tle = tles.Where(t => t.getName().Contains("97")).ToArray()[0];
            One_Sgp4.Sgp4 sgp4Propagator = new One_Sgp4.Sgp4(tle, 1); 
            One_Sgp4.EpochTime startTime = new One_Sgp4.EpochTime(0, 0, 0, 2018, 4, 7);
            One_Sgp4.EpochTime stopTime = new One_Sgp4.EpochTime(0, 59, 0, 2018,4, 7);
            sgp4Propagator.runSgp4Cal(startTime, stopTime, 1);
            
            List<One_Sgp4.Sgp4Data> resultDataList = new List<One_Sgp4.Sgp4Data>();
            resultDataList = sgp4Propagator.getRestults();

            for (int i = 0; i < 59; i++)
            {
                One_Sgp4.EpochTime t = new One_Sgp4.EpochTime(0, i, 0, 2018, 4, 7);
                One_Sgp4.Coordinate c= One_Sgp4.SatFunctions.calcSatSubPoint(t, resultDataList[i], 1);
                //System.Diagnostics.Debug.WriteLine(t.toDateTime());
                System.Diagnostics.Debug.WriteLine("lat:{0} ,lon:{1}",c.getLatetude(), c.getLongitude());
            }

**Comment by 1manprojects** [comment]
Hello, thanks for the info. Im currnetly investigating the bug however im having a hard time finding the error. Kann you provide me with the TLE Data of the irdidium 97 satelite you used and your output of PyEphem.

**Comment by 1manprojects** [comment]
The calculations for the subpoint have been updated.
