### ISSUE TITLE
How to get satellite velocity in km/h as well as pass predictions given an observer location

### ISSUE THREAD

**Issue by edetoc** [1manprojects/one_Sgp4#4]
Many thanks for this library. I'm using it now for tracking the ISS on a Map in a Windows UWP app.
I have a couple of questions:
1) How can I get the satellite velocity in km/h ?
2) How can I use the library to do pass predictions given an observer location?

thank you

**Comment by 1manprojects** [comment]
The Velocity vectors are outputted in km/s in the ECI (Earth-centered inertial) coordinate Frame. Now depending on your refernce frame you would need to transform them to the new Refernce. Do you want to have the speed of the satellite from the view of an observer on earth or do you just need the velocity of the satellite in ECI as a magnitude value of the vector itself. The Later one is simple velocity = sqrt(x*x+y*y+z*z). 

To your second question do you want to know were a satellite is going to be from a given location? If yes there is the SatFunctions.calcSphericalCoordinate( coordinate of the observer, time, Satellite pos x,y,z at given time) this will return a Point3d object that contains Range from the observer to given point, Azimuth from the coordinate and elevation (Horizontal Coordinate System https://en.wikipedia.org/wiki/Horizontal_coordinate_system).
To predict a pass you can also use the SatFunctions.isSatVisible(Coordinate on ground, minimum elevation at that location, time, Satellite pos data at that time point) to check if the satellite is visible at that point at the given time point. This schould allow you to predict the exact position of a satellite over an observer for any given satellite coordinates.

**Comment by edetoc** [comment]
Many thanks for your quick response. 
For question 1, I will go for the simple velocity. I found that I can get the x,y,z velocity vector from Sgp4Data.vel. So I should be fine.
For question 2, I'd like to be able to get let's say the next 10 visible passes from any given longitude/latitude position on earth (in my app this will be the user's location).

**Comment by 1manprojects** [comment]
Currently there is no way to just ask for the next 10 passes. But you could calculate the position of the satellite check if it is visible at the given time and then repeat until you have your 10 passes. For the future i could implement that feature but that could take some time

**Comment by edetoc** [comment]
thank you. would be great if you can implement this in a future release. Maybe this link can help you (if you don't already know it):
https://www.danrw.com/sgp4/
