### ISSUE TITLE
wrong value for Coordinate.getHeight() ?

### ISSUE THREAD

**Issue by edetoc** [1manprojects/one_Sgp4#5]
I'm using the library to track the ISS based on TLE elements obtained from https://www.celestrak.com/NORAD/elements/stations.txt
The library gives correct values for longitude/latitude and velocity. However I believe there's a glitch in the Height calculation (Coordinate.getHeight() ). I assume the Height is in Km. the Height value is different from what I can see here: http://www.esa.int/Our_Activities/Human_Spaceflight/International_Space_Station/Where_is_the_International_Space_Station
For instance, when the ESA url shows Altitude of 417 km, getHeight() returns 407 km.

thanks,
Eric

**Comment by 1manprojects** [comment]
Yes the height is in km. Also you are correct the height is not being calculated correctly it has a slight offset since it at its current state will always use the WGS_72 constants instead of WGS_84. This will be fixes soon however i cannot provide a time frame.

**Comment by edetoc** [comment]
thank you.

**Comment by 1manprojects** [comment]
Has been fixed with commit dddc3c6
